// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: game.proto

package gampepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	StreamUserStatusChange(ctx context.Context, in *UserStatusChangeRequest, opts ...grpc.CallOption) (UserService_StreamUserStatusChangeClient, error)
	StreamPlayerJoinedStatus(ctx context.Context, in *PlayerInPartyRequest, opts ...grpc.CallOption) (UserService_StreamPlayerJoinedStatusClient, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) StreamUserStatusChange(ctx context.Context, in *UserStatusChangeRequest, opts ...grpc.CallOption) (UserService_StreamUserStatusChangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], "/protos.UserService/StreamUserStatusChange", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceStreamUserStatusChangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_StreamUserStatusChangeClient interface {
	Recv() (*UserStatusChangeResponse, error)
	grpc.ClientStream
}

type userServiceStreamUserStatusChangeClient struct {
	grpc.ClientStream
}

func (x *userServiceStreamUserStatusChangeClient) Recv() (*UserStatusChangeResponse, error) {
	m := new(UserStatusChangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) StreamPlayerJoinedStatus(ctx context.Context, in *PlayerInPartyRequest, opts ...grpc.CallOption) (UserService_StreamPlayerJoinedStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], "/protos.UserService/StreamPlayerJoinedStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceStreamPlayerJoinedStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_StreamPlayerJoinedStatusClient interface {
	Recv() (*PlayersInPartyResponse, error)
	grpc.ClientStream
}

type userServiceStreamPlayerJoinedStatusClient struct {
	grpc.ClientStream
}

func (x *userServiceStreamPlayerJoinedStatusClient) Recv() (*PlayersInPartyResponse, error) {
	m := new(PlayersInPartyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	StreamUserStatusChange(*UserStatusChangeRequest, UserService_StreamUserStatusChangeServer) error
	StreamPlayerJoinedStatus(*PlayerInPartyRequest, UserService_StreamPlayerJoinedStatusServer) error
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) StreamUserStatusChange(*UserStatusChangeRequest, UserService_StreamUserStatusChangeServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamUserStatusChange not implemented")
}
func (UnimplementedUserServiceServer) StreamPlayerJoinedStatus(*PlayerInPartyRequest, UserService_StreamPlayerJoinedStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamPlayerJoinedStatus not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_StreamUserStatusChange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserStatusChangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).StreamUserStatusChange(m, &userServiceStreamUserStatusChangeServer{stream})
}

type UserService_StreamUserStatusChangeServer interface {
	Send(*UserStatusChangeResponse) error
	grpc.ServerStream
}

type userServiceStreamUserStatusChangeServer struct {
	grpc.ServerStream
}

func (x *userServiceStreamUserStatusChangeServer) Send(m *UserStatusChangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_StreamPlayerJoinedStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayerInPartyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).StreamPlayerJoinedStatus(m, &userServiceStreamPlayerJoinedStatusServer{stream})
}

type UserService_StreamPlayerJoinedStatusServer interface {
	Send(*PlayersInPartyResponse) error
	grpc.ServerStream
}

type userServiceStreamPlayerJoinedStatusServer struct {
	grpc.ServerStream
}

func (x *userServiceStreamPlayerJoinedStatusServer) Send(m *PlayersInPartyResponse) error {
	return x.ServerStream.SendMsg(m)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamUserStatusChange",
			Handler:       _UserService_StreamUserStatusChange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamPlayerJoinedStatus",
			Handler:       _UserService_StreamPlayerJoinedStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
